version: "3"
services:
  hub:
    image: selenium/hub:4.1.2
    ports:
      - "4444:4444"
      - "4443:4443"
      - "4442:4442"
  chrome:
    image: selenium/node-chrome:4.1.2
    shm_size: '2g'        
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    image: selenium/node-firefox:4.1.2
    shm_size: '2g'   
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  search_module:
    image: raghudockernew/my-selenium-docker:new3
    depends_on:
      - chrome
      - firefox
    environment:
      - "BROWSER = chrome"
      - "HUB_HOST = hub"
      - "MODULE = search-module.xml"
    volumes:
      - "./search:/usr/share/udemy/test-output"